import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import logo from '@/assets/images/logo-2.png';
const Navbar = () => {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsxs("nav", { className: "bg-gray-800", children: [_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(Link, { to: "/", className: "flex items-center", children: _jsx("img", { className: "h-16 w-20", src: logo, alt: "Freelancer" }) }) }), _jsxs("div", { className: "hidden md:flex items-center space-x-4", children: [_jsx(Link, { to: "/signin", className: "text-gray-300 hover:text-white px-3 py-2", children: "Sign In" }), _jsx(Link, { to: "/signup", className: "text-gray-300 hover:text-white px-3 py-2", children: "Sign Up" }), _jsx(Link, { to: "/post-project", className: "bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-md", children: "Post a Project" })] }), _jsx("div", { className: "md:hidden", children: _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none", children: _jsx("svg", { className: "h-6 w-6", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: isOpen ? (_jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M6 18L18 6M6 6l12 12" })) : (_jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M4 6h16M4 12h16M4 18h16" })) }) }) })] }) }), isOpen && (_jsx("div", { className: "md:hidden", children: _jsxs("div", { className: "px-2 pt-2 pb-3 space-y-1", children: [_jsx(Link, { to: "/hire", className: "block px-3 py-2 text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 rounded-md", children: "Hire freelancers" }), _jsx(Link, { to: "/find-work", className: "block px-3 py-2 text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 rounded-md", children: "Find work" }), _jsx(Link, { to: "/solutions", className: "block px-3 py-2 text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 rounded-md", children: "Solutions" }), _jsx(Link, { to: "/login", className: "block px-3 py-2 text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 rounded-md", children: "Log In" }), _jsx(Link, { to: "/signup", className: "block px-3 py-2 text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 rounded-md", children: "Sign Up" }), _jsx(Link, { to: "/post-project", className: "block px-3 py-2 text-base font-medium bg-green-600 text-white hover:bg-green-700 rounded-md", children: "Post a Project" })] }) }))] }));
};
export default Navbar;
