import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Offcanvas from "@/components/ui/Offcanvas";
import ViewButton from "@/components/ui/ViewButton";
import { formatDate } from "@/utils/format";
import { useState } from "react";
const ClientProjects = ({ data }) => {
    const [rightOffcanvas, setRightOffcanvas] = useState(false);
    return (_jsx("div", { className: "bg-white dark:bg-gray-800 p-8 mb-6 shadow-md border border-gray-100 dark:border-gray-700 rounded-xl", children: data?.client?.projects?.length ? (_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full border-collapse border border-gray-200 dark:border-gray-700 text-sm", children: [_jsx("thead", { className: "bg-gray-100 dark:bg-gray-700 text-left", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: "#" }), _jsx("th", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: "Project Name" }), _jsx("th", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: "Created At" }), _jsx("th", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: "Actions" })] }) }), _jsx("tbody", { children: data.client.projects.map((project, idx) => (_jsxs("tr", { className: "hover:bg-gray-50 dark:hover:bg-gray-900 transition-colors", children: [_jsx("td", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: idx + 1 }), _jsx("td", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: project.title || "N/A" }), _jsx("td", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: formatDate(project.createdAt) }), _jsx("td", { className: "px-4 py-3 border border-gray-200 dark:border-gray-700", children: _jsxs("div", { children: [_jsx(ViewButton, { onClick: () => setRightOffcanvas(true) }), _jsx(Offcanvas, { isOpen: rightOffcanvas, onClose: () => setRightOffcanvas(false), position: "right", title: "Right Offcanvas", size: "lg", children: _jsx("p", { className: "text-gray-600", children: "This is a basic right-positioned offcanvas panel. It slides in from the right side of the screen." }) })] }) })] }, idx))) })] }) })) : (_jsx("p", { className: "text-gray-500 dark:text-gray-400", children: "No project info found" })) }));
};
export default ClientProjects;
