import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Bars3Icon, BellIcon, Squares2X2Icon, UserCircleIcon, MoonIcon, GlobeAltIcon, BellAlertIcon, MagnifyingGlassIcon } from '@heroicons/react/24/outline';
import { useTheme } from '@/hooks/useTheme';
import { useNavigate } from 'react-router-dom';
import { getUser } from '@/lib/auth';
import { useAuth } from '@/hooks/useAuth';
const Header = ({ onMenuClick }) => {
    const navigate = useNavigate();
    const { logout } = useAuth();
    const { isDarkMode, toggleTheme } = useTheme();
    const [isNotificationsOpen, setIsNotificationsOpen] = useState(false);
    const [isSettingsOpen, setIsSettingsOpen] = useState(false);
    const [isProfileOpen, setIsProfileOpen] = useState(false);
    const [isMobileSearchOpen, setIsMobileSearchOpen] = useState(false);
    const [searchValue, setSearchValue] = useState('');
    return (_jsxs("header", { className: "w-full bg-white dark:bg-gray-800 shadow-sm relative", children: [isMobileSearchOpen && (_jsx("div", { className: "fixed inset-0 z-50 flex flex-col bg-black bg-opacity-40", children: _jsxs("div", { className: "bg-white dark:bg-gray-800 p-4 flex items-center shadow-md", children: [_jsx(MagnifyingGlassIcon, { className: "h-5 w-5 text-gray-500 dark:text-gray-300 mr-2" }), _jsx("input", { type: "text", className: "flex-1 bg-transparent outline-none text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-md", placeholder: "Search...", value: searchValue, onChange: e => setSearchValue(e.target.value), autoFocus: true }), _jsx("button", { onClick: () => setIsMobileSearchOpen(false), className: "ml-2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200", children: "\u2715" })] }) })), _jsxs("div", { className: "flex items-center justify-between h-16 px-4 lg:px-6", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("button", { onClick: onMenuClick, className: "p-2 rounded-md text-gray-500 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-300 focus:outline-none", children: _jsx(Bars3Icon, { className: "h-6 w-6" }) }), _jsx("div", { className: "hidden sm:flex items-center ml-2", children: _jsxs("div", { className: "relative", children: [_jsx(MagnifyingGlassIcon, { className: "h-5 w-5 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" }), _jsx("input", { type: "text", className: "pl-10 pr-3 py-2 rounded-md border border-gray-200 dark:border-gray-700 bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500", placeholder: "Search...", value: searchValue, onChange: e => setSearchValue(e.target.value) })] }) }), _jsx("button", { className: "sm:hidden p-2 rounded-md text-gray-500 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-300 focus:outline-none", onClick: () => setIsMobileSearchOpen(true), children: _jsx(MagnifyingGlassIcon, { className: "h-6 w-6" }) })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "relative", children: [_jsxs("button", { onClick: () => {
                                            setIsNotificationsOpen(!isNotificationsOpen);
                                            setIsSettingsOpen(false);
                                            setIsProfileOpen(false);
                                        }, className: "p-2 rounded-md text-gray-500 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-300 focus:outline-none relative", children: [_jsx(BellIcon, { className: "h-6 w-6" }), _jsx("span", { className: "absolute top-1 right-1 h-2 w-2 bg-red-500 rounded-full" })] }), isNotificationsOpen && (_jsxs("div", { className: "absolute right-0 mt-2 w-80 bg-white dark:bg-gray-800 rounded-lg shadow-lg py-2 z-50", children: [_jsx("div", { className: "px-4 py-2 border-b border-gray-200 dark:border-gray-700", children: _jsx("h3", { className: "text-sm font-semibold text-gray-900 dark:text-white", children: "Notifications" }) }), _jsxs("div", { className: "max-h-96 overflow-y-auto", children: [_jsxs("div", { className: "px-4 py-3 hover:bg-gray-100 dark:hover:bg-gray-700", children: [_jsx("p", { className: "text-sm text-gray-900 dark:text-white", children: "New user registration" }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400", children: "2 minutes ago" })] }), _jsxs("div", { className: "px-4 py-3 hover:bg-gray-100 dark:hover:bg-gray-700", children: [_jsx("p", { className: "text-sm text-gray-900 dark:text-white", children: "System update completed" }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400", children: "1 hour ago" })] })] })] }))] }), _jsxs("div", { className: "relative", children: [_jsx("button", { onClick: () => {
                                            setIsSettingsOpen(!isSettingsOpen);
                                            setIsNotificationsOpen(false);
                                            setIsProfileOpen(false);
                                        }, className: "p-2 rounded-md text-gray-500 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-300 focus:outline-none", children: _jsx(Squares2X2Icon, { className: "h-6 w-6" }) }), isSettingsOpen && (_jsxs("div", { className: "absolute right-0 mt-2 w-64 bg-white dark:bg-gray-800 rounded-lg shadow-lg py-2 z-50", children: [_jsx("div", { className: "px-4 py-2 border-b border-gray-200 dark:border-gray-700", children: _jsx("h3", { className: "text-sm font-semibold text-gray-900 dark:text-white", children: "App Settings" }) }), _jsxs("div", { className: "py-2", children: [_jsxs("button", { onClick: toggleTheme, className: "w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center", children: [_jsx(MoonIcon, { className: "h-5 w-5 mr-2" }), isDarkMode ? 'Light Mode' : 'Dark Mode'] }), _jsxs("button", { className: "w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center", children: [_jsx(GlobeAltIcon, { className: "h-5 w-5 mr-2" }), "Language Settings"] }), _jsxs("button", { className: "w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center", children: [_jsx(BellAlertIcon, { className: "h-5 w-5 mr-2" }), "Notification Settings"] })] })] }))] }), _jsxs("div", { className: "relative", children: [_jsx("button", { onClick: () => {
                                            setIsProfileOpen(!isProfileOpen);
                                            setIsSettingsOpen(false);
                                            setIsNotificationsOpen(false);
                                        }, className: "p-2 rounded-md text-gray-500 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-300 focus:outline-none flex items-center", children: _jsx(UserCircleIcon, { className: "h-7 w-7" }) }), isProfileOpen && (_jsxs("div", { className: "absolute right-0 mt-2 w-56 bg-white dark:bg-gray-800 rounded-lg shadow-lg py-2 z-50", children: [_jsxs("div", { className: "px-4 py-2 border-b border-gray-200 dark:border-gray-700 flex items-center", children: [_jsx(UserCircleIcon, { className: "h-8 w-8 text-gray-500 dark:text-gray-300 mr-2" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-gray-900 dark:text-white", children: getUser()?.name }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400", children: getUser()?.email })] })] }), _jsxs("button", { className: "w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center", onClick: () => navigate('/users/profile'), children: [_jsx(UserCircleIcon, { className: "h-5 w-5 mr-2" }), "Profile"] }), _jsxs("button", { className: "w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center", children: [_jsx(Bars3Icon, { className: "h-5 w-5 mr-2" }), "My Dashboard"] }), _jsxs("button", { className: "w-full px-4 py-2 text-left text-sm text-red-600 dark:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center", onClick: async () => {
                                                    await logout();
                                                    navigate('/admin/login');
                                                }, children: [_jsx("svg", { className: "h-5 w-5 mr-2", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M17 16l4-4m0 0l-4-4m4 4H7" }) }), "Logout"] })] }))] })] })] })] }));
};
export default Header;
